### PR TITLE
Added Coffeescript

### PR DESCRIPTION
**Pull request by jwerre**
Added tripple quotes to body and added support for coffeescript

### CODE REVIEW

**Comment by james2doyle** [comment]
This seems like good work. But I think mixing the normal javascript snippets with coffee script snippets is strange.

Why not have a separate repo that is `jquery-coffeescript-snippets`?

**Comment by jwerre** [comment]
ugh... now you tell me

**Comment by james2doyle** [comment]
Well to be fair, no one asked for you to contribute a whole set of coffee script snippets. If you had asked before I would have gave the same answer.

Also, your repo still exists with the additional code. So nothing is lost. You can add a repository to Atom and then install the package right from there.

**Comment by jwerre** [comment]
I'll strip these out and put them in their own files. Pardon my griping :)

**Comment by t-matsu-j** [comment]
jwerre, i need this commit. i want you to add a repo with these code to Atom.

**Comment by james2doyle** [comment]
@jwerre you should add a new project to the atom package repo. Something like jquery-coffeescript. Sounds like a lot of people are looking for that

**Pull request closed without merging**
